USE tryit_diet_db;
TRUNCATE TABLE ingredients;
INSERT INTO ingredients (name)
VALUES
('erythritol'),
('xylitol'),
('splenda'),
('honey'),
('molasses'),
('white sugar'),
('brown sugar'),
('white vinegar'),
('balsamic vinegar'),
('apple cider vinegar'),
('rice vinegar'),
('baking soda'),
('baking powder'),
('cocoa powder'),
('olive oil'),
('peanut oil'),
('coconut oil'),
('spray oil'),
('cooking spray'),
('sea salt'),
('milled pepper'),
('basil'),
('oregano'),
('parsley'),
('garlic powder'),
('onion powder'),
('cinnamon'),
('nutmeg'),
('chili'),
('cumin'),
('thyme'),
('fennel'),
('vanilla extract'),
('almond extract'),
('maple extract'),
('mint extract'),
('orange extract'),
('rum extract'),
('almond flour'),
('coconut flour'),
('flour'),
('almond meal'),
('coconut'),
('protein powder'),
('flax seed meal'),
('thickener'),
('chia seeds'),
('soy sauce'),
('worcestershire sauce'),
('kitchen bouquet'),
('onion'),
('green onions'),
('garlic'),
('jalapeno slices'),
('black olives'),
('ro-tel'),
('iced tea bags'),
('mint tea bags'),
('pizza sauce'),
('organic beef broth'),
('organic chicken broth'),
('pumpkin seeds'),
('sunflower seeds'),
('macadamia nuts'),
('almonds'),
('walnuts'),
('pine nuts'),
('cashews'),
('chestnuts'),
('pecans'),
('tomatoes'),
('sun-dried tomatoes'),
('roasted red peppers'),
('artichoke hearts'),
('pesto'),
('alfredo sauce'),
('pumpkin'),
('feta'),
('medium cheddar'),
('sharp cheddar'),
('parmesan'),
('cream cheese'),
('shredded mozzarella'),
('heavy whipping cream'),
('butter'),
('sour cream'),
('beef'),
('eggs'),
('pasta'),
('multigrain pasta'),
('chicken'),
('bacon'),
('salami'),
('pepperoni'),
('green beans'),
('grape tomatoes'),
('pickles'),
('wonton wrappers'),
('cucumber'),
('zucchini'),
('cauliflower'),
('spinach'),
('mushrooms'),
('lettuce'),
('green olives'),
('ketchup'),
('yellow mustard'),
('relish'),
('brussels sprouts'),
('carrots'),
('gingerroot'),
('lemon'),
('jalapeno'),
('jalapeno pepper jelly'),
('red bell peppers'),
('lime'),
('blueberries'),
('strawberries'),
('barbecue sauce'),
('mayonnaise'),
('snap peas'),
('salt'),
('pepper'),
('gluten-free pasta'),
('whole wheat pasta'),
('water'),
('corn'),
('poblano peppers'),
('serrano peppers'),
('corn starch'),
('cilantro'),
('bay leaf'),
('star anise'),
('cranberry'),
('pork'),
('cornflake'),
('grapefruit');