USE tryit_diet_db;
TRUNCATE TABLE ingredients;
INSERT INTO ingredients (name)
VALUES
('erythritol'),
('xylitol'),
('splenda'),
('honey'),
('molasses'),
('white sugar'),
('brown sugar'),
('white vinegar'),
('balsamic vinegar'),
('apple cider vinegar'),
('baking soda'),
('baking powder'),
('cocoa powder'),
('olive oil'),
('peanut oil'),
('coconut oil'),
('spray oil'),
('sea salt'),
('milled pepper'),
('basil'),
('oregano'),
('parsley'),
('garlic powder'),
('onion powder'),
('cinnamon'),
('nutmeg'),
('chili'),
('cumin'),
('thyme'),
('fennel'),
('vanilla extract'),
('almond extract'),
('maple extract'),
('mint extract'),
('orange extract'),
('rum extract'),
('almond flour'),
('coconut flour'),
('flour'),
('almond meal'),
('coconut'),
('protein powder'),
('flax seed meal'),
('thickener'),
('chia seeds'),
('soy sauce'),
('worcestershire sauce'),
('kitchen bouquet'),
('onion'),
('green onion'),
('garlic'),
('jalapeno slices'),
('black olives'),
('ro-tel'),
('iced tea bags'),
('mint tea bags'),
('pizza sauce'),
('organic beef broth'),
('organic chicken broth'),
('pumpkin seeds'),
('sunflower seeds'),
('macadamia nuts'),
('almonds'),
('walnuts'),
('pine nuts'),
('cashews'),
('pecans'),
('sun-dried tomatoes'),
('roasted red peppers'),
('artichoke hearts'),
('pesto'),
('alfredo sauce'),
('pumpkin'),
('feta'),
('medium cheddar'),
('sharp cheddar'),
('parmesan'),
('cream cheese'),
('shredded mozzarella'),
('heavy whipping cream'),
('butter'),
('sour cream'),
('beef'),
('eggs'),
('pasta'),
('chicken'),
('bacon'),
('salami'),
('pepperoni'),
('green beans'),
('grape tomatoes'),
('pickles'),
('cucumber'),
('zucchini'),
('cauliflower'),
('spinach'),
('mushrooms'),
('lettuce'),
('lemon juice'),
('green olives'),
('mayonnaise'),
('ketchup'),
('yellow mustard'),
('relish'),
('brussels sprouts'),
('carrots'),
('ginger root'),
('green'),
('red bell peppers'),
('lime juice'),
('blueberries'),
('strawberries'),
('barbecue sauce'),
('mayonnaise'),
('snap peas');